# -*- coding: utf-8 -*-
"""Internship_task#02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRnh-wwdbxNaRnU3ZwZymTdPbX87HaaV
"""

#importing pandas library
import pandas as pd
#import matplotlib
import matplotlib.pyplot as plt
#importing seaborn library
import seaborn as sns

#loading data
titanic=pd.read_csv('/Titanic.csv')
df=pd.DataFrame(titanic)

# View first five rows of the dataset
titanic.head()

titanic.isnull().sum()

#Total Passenger
print(df['sex'].count())

df.dropna(subset=['sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'alone', 'survived'],inplace= True)

df['embarked'] = df['embarked'].replace({'s': 'Southampton', 'c': 'Cherbourg', 'q': 'Queenstown'})

#Total Survived
survived_counts = df['survived'].value_counts()
print(survived_counts)

gender_counts = df['sex'].value_counts()
print(gender_counts)

#Plot Age & Fare
scatter = plt.scatter(df['age'], df['fare'])
plt.xlabel('Age')
plt.ylabel('Fare')
plt.grid(True)
plt.title('Age by Fare')
plt.show()

survived_sex_counts = df.groupby(['sex', 'sex']).size().unstack()

# Plotting
survived_sex_counts.plot(kind='bar', stacked=True,colormap='plasma',)
plt.ylabel('Sext')
plt.xlabel('Sex')
plt.grid(True)
plt.title('Sex by Sex')
plt.show()

# Plot Sex by Sex
sex_counts = df['sex'].value_counts()
plt.pie(sex_counts, labels=sex_counts.index, autopct='%1.1f%%',startangle=90)
plt.title('Distribution of Sex')
plt.axis('equal')
plt.show()

# Plot Survived & Sex
sns.countplot(data=df, x='sex', hue='survived',palette='inferno')
plt.ylabel('Count')
plt.xlabel('Sex')
plt.grid(True)
plt.title('Survived & Sex')
plt.show()

# Plot Count by Embark & Class
count = df.groupby(['embarked', 'class']).size().unstack(fill_value=0)

count.plot(kind='bar', stacked=True, colormap='viridis', figsize=(10, 6))
plt.xlabel('Embarked')
plt.ylabel('Class')
plt.grid(True)
plt.title('Count by Embark & Class')
plt.show()

# Plot Embarked & Survived
sns.countplot(data=df, x='embarked', hue='survived',palette='cividis')
plt.xlabel('Embarked')
plt.ylabel('Survived')
plt.grid(True)
plt.title('Embarked & Survived')
plt.show()

# Plot Fare by Age And Sex
sns.lineplot(data=df, x="age", y="fare", hue="sex", palette="viridis")
plt.xlabel('Age')
plt.ylabel('Fare')
plt.grid(True)
plt.title('Fare by Age And Sex')
plt.show()

# Plot Count by Class & Sex

counts = df.groupby(['class', 'sex']).size().unstack(fill_value=0)

counts.plot(kind='bar', stacked=True, colormap='coolwarm')  # You can choose your colors

plt.xlabel('Class')
plt.ylabel('Total Count')
plt.title('Distribution of Class by Sex')
plt.legend(title='Sex')
plt.grid(True)
plt.show()

# Plot Fare by Survived And Age
sns.scatterplot(data=df, x="age", y="fare", hue="survived", palette="twilight")
plt.xlabel('Age')
plt.ylabel('Fare')
plt.grid(True)
plt.title('Fare by Survived And Age')
plt.show()